name: Create Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set project version based on tag
        run: mvn versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/EditeurDeTexte-${{ github.ref_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
